import Head from 'next/head'
import { useRouter } from 'next/router'
import { MainLayout } from 'layouts/main'
import Loader from 'components/Loader'
import { gql, useQuery } from '@apollo/client'
import { Box } from '@chakra-ui/react'

const GET_LOCATION = gql`
  query location($id: ID!) {
    location(id: $id) {
      id
      name
      type
      dimension

      residents {
        id
        name
        species
      }
      created
    }
  }
`

const Location = () => {
  const router = useRouter()
  const { id } = router.query

  const { loading, error, data } = useQuery<CharacterData>(GET_LOCATION, {
    variables: { id },
  })

  if (loading) return <Loader />
  if (error) return <h1>Error! {error.message}</h1>
  if (!data) return <h1>No data</h1>

  console.log({ data })

  return (
    <MainLayout>
      <Head>
        <title>Rick and Morty Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <Box
        w='100%'
        h='calc(100vh - 80px)'
        display='flex'
        justifyContent='center'
        alignItems='center'>
        Location {id}
      </Box>
    </MainLayout>
  )
}

export default Location
