import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from 'components/Header'
import { CharacterList } from 'components/Character/CharacterList'
import { Box } from '@chakra-ui/react'
import { Character } from 'components/Character'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Turpial Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box w='100%'>
        <Header />
        <Character />
      </Box>
    </>
  )
}

export default Home
