import type { NextPage } from 'next'
import { Box, Center } from '@chakra-ui/react'
import Loader from 'components/Loader'
import { MainLayout } from 'layouts/main'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useQuery } from '@apollo/client'

const Episode: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  // const { loading, error, data } = useQuery<CharacterData>(GET_CHARACTER, {
  //   variables: { id },
  // })

  // if (loading)
  //   return (

  //       <Loader />

  //   )
  // if (error) return <h1>Error! {error.message}</h1>
  // if (!data) return <h1>No data</h1>

  // console.log({ data })
  return (
    <MainLayout>
      <Head>
        <title>Rick and Morty Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>

      <Box
        w='100%'
        h='calc(100vh - 80px)'
        display='flex'
        justifyContent='center'
        alignItems='center'>
        {id}
      </Box>
    </MainLayout>
  )
}

export default Episode
