import type { NextPage } from 'next'
import { Box, Center } from '@chakra-ui/react'
import Loader from 'components/Loader'
import { MainLayout } from 'layouts/main'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { gql, useQuery } from '@apollo/client'

const GET_EPISODE = gql`
  query episode($id: ID!) {
    episode(id: $id) {
      id
      name
      air_date
      episode
      characters {
        id
        name
        species
      }
    }
  }
`

const Episode: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const { loading, error, data } = useQuery<CharacterData>(GET_EPISODE, {
    variables: { id },
  })

  if (loading) return <Loader />
  if (error) return <h1>Error! {error.message}</h1>
  if (!data) return <h1>No data</h1>

  console.log({ data })
  return (
    <MainLayout>
      <Head>
        <title>Rick and Morty Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>

      <Box
        w='100%'
        h='calc(100vh - 80px)'
        display='flex'
        justifyContent='center'
        alignItems='center'>
        Episode {id}
      </Box>
    </MainLayout>
  )
}

export default Episode
