import { gql, useQuery } from '@apollo/client'
import { Box, Button, Center, Grid } from '@chakra-ui/react'
import { EpisodeoCard } from 'components/EpisodeoCard'
import Loader from 'components/Loader'
import { MainLayout } from 'layouts/main'
import Head from 'next/head'
import { EpisodeData } from 'utils/interfaces/episodes'

const GET_ALL_EPISODES = gql`
  query Episodes($page: Int!) {
    episodes(page: $page) {
      info {
        next
        prev
        pages
        count
      }
      results {
        id
        name
        episode
      }
    }
  }
`

export default function Episodes() {
  const { loading, error, data, refetch } = useQuery<EpisodeData>(
    GET_ALL_EPISODES,
    {
      variables: { page: 1 },
    },
  )

  if (loading) return <Loader />
  if (error) return <h1>Error! {error.message}</h1>
  if (!data) return <h1>No data</h1>
  console.log({ data })

  return (
    <MainLayout>
      <Head>
        <title>Rick and Morty Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>

      <Grid
        id='characters_grid'
        templateColumns='repeat(auto-fit, minmax(min(100%, 25rem), 1fr))'
        justifyItems='center'
        gap={2}>
        {data.episodes?.results.map((episode) => {
          return <EpisodeoCard key={episode.id} episode={episode} />
        })}
      </Grid>
      <Center my={6} gap={8}>
        <Button
          name='prev_page'
          onClick={() => refetch({ page: data?.episodes?.info.prev })}>
          Prev page
        </Button>

        <Button
          name='next_page'
          onClick={() => refetch({ page: data?.episodes?.info.next })}>
          Next page
        </Button>
      </Center>
    </MainLayout>
  )
}
